services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mangatech_backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mangatech_frontend
    ports:
      - "3000:80"